# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 64dea12582f09912c13c65e73c8f63a4f25c86dc9efa672555cd84420108423b6ac378b93a862dd2f8a24f1488d8924169cf3762a3f367ae18b3418c648dc1b6

test:
  secret_key_base: dfc577ed7474bb8447ab3f588670576743abdfc5542da801db335fd6927158863795be9bcd10444790fbf6ff33bebae72c8444f58d5d0d2646ba5d47c0bd321a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
